basePath: /
host: localhost:3000
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is a training API using Gin + GORM + PostgreSQL
  license:
    name: MIT
  title: Go Training API
  version: "1.0"
paths: {}
swagger: "2.0"
